// In-app notifications. Generated by task events (chat message, assignment,
// status change) and read via the notification bell. Notification delivery is
// best-effort: a failure here never breaks the underlying write.

import type { Notification } from '../domain/entities';
import { forbidden } from '../domain/errors';
import { newId } from '../domain/ids';
import type { NotificationRepository } from '../repositories/interfaces';
import { nowIso, type Clock, type RequestContext } from './context';

export interface NotifyInput {
  type: string;
  title: string;
  taskId?: string;
  actorUserId?: string;
}

export class NotificationService {
  constructor(
    private readonly repo: NotificationRepository,
    private readonly clock: Clock,
  ) {}

  /** Best-effort create. Skips self-notifications and swallows errors. */
  async notify(userId: string, input: NotifyInput): Promise<void> {
    if (!userId || input.actorUserId === userId) return;
    const n: Notification = {
      id: newId('notification'),
      userId,
      type: input.type,
      title: input.title,
      read: false,
      createdAt: nowIso(this.clock),
    };
    if (input.taskId) n.taskId = input.taskId;
    if (input.actorUserId) n.actorUserId = input.actorUserId;
    try {
      await this.repo.create(n);
    } catch {
      /* best-effort: never break the triggering action */
    }
  }

  /** Notify several recipients, de-duplicated, excluding the actor. */
  async notifyMany(userIds: string[], input: NotifyInput): Promise<void> {
    const unique = [...new Set(userIds)];
    for (const id of unique) await this.notify(id, input);
  }

  async list(ctx: RequestContext, limit = 30): Promise<Notification[]> {
    return this.repo.listByUser(ctx.actor.id, limit);
  }

  async unreadCount(ctx: RequestContext): Promise<number> {
    const list = await this.repo.listByUser(ctx.actor.id, 100);
    return list.filter((n) => !n.read).length;
  }

  async markRead(ctx: RequestContext, id: string): Promise<void> {
    const n = await this.repo.getById(id);
    if (!n || n.userId !== ctx.actor.id) throw forbidden('Not your notification.');
    if (!n.read) await this.repo.update(id, { read: true });
  }

  async markAllRead(ctx: RequestContext): Promise<void> {
    const list = await this.repo.listByUser(ctx.actor.id, 200);
    for (const n of list) if (!n.read) await this.repo.update(n.id, { read: true });
  }
}
